## AoB: from current praqma/network-multitool:extra
#FROM praqma/network-multitool:extra
FROM praqma/network-multitool:73580d2

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
COPY requirements-py.txt /root/
RUN pip install --no-cache-dir -r /root/requirements-py.txt

COPY dist/mcast /root/
COPY libs/* /root/
COPY mcast.py /bin/mcast

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
ENTRYPOINT ["/bin/sh", "/docker-entrypoint.sh"]
